language: node_js
node_js:
  - "7.3.0"
services:
  - mongodb
  - redis-server
before_script:
  - "mkdir -p ./.config && cp ./.ci-files/config.yml ./.config"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
