nodeLinker: pnp
pnpMode: loose

supportedArchitectures:
  os: ["current", "darwin", "linux"]
  cpu: ["current", "x64", "arm64"]
  libc: ["current", "glibc", "musl"]

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
