compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

npmScopes:
  iceshrimp:
    npmRegistryServer: "https://iceshrimp.dev/api/packages/iceshrimp/npm/"

packageExtensions:
  consolidate@^0.16.0:
    dependencies:
      ejs: ^3.1.7
      pug: 3.0.2
  debug@*:
    dependencies:
      supports-color: ^8.0.0
  fix-esm@1.0.1:
    dependencies:
      multer: 1.4.4-lts.1
  node-fetch@2.6.12:
    dependencies:
      encoding: ^0.1.13
  ws@8.13.0:
    dependencies:
      bufferutil: ^4.0.1

pnpMode: strict

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux
