nodeLinker: pnp
pnpMode: loose

supportedArchitectures:
  os: ["current", "darwin", "linux"]
  cpu: ["current", "x64", "arm64"]
  libc: ["current", "glibc", "musl"]

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

npmScopes:
  iceshrimp:
    npmRegistryServer: "https://iceshrimp.dev/api/packages/iceshrimp/npm/"

packageExtensions:
  debug@*:
    dependencies:
      "supports-color": ^8.0.0
  node-fetch@2.6.12:
    dependencies:
      "encoding": ^0.1.13
  ws@8.13.0:
    dependencies:
      "bufferutil": ^4.0.1
  fix-esm@1.0.1:
    dependencies:
      "multer": 1.4.4-lts.1
  consolidate@^0.16.0:
    dependencies:
      "pug": 3.0.2
