compressionLevel: mixed
enableGlobalCache: false
nodeLinker: pnp
pnpMode: strict

npmScopes:
  iceshrimp:
    npmRegistryServer: "https://iceshrimp.dev/api/packages/iceshrimp/npm/"

packageExtensions:
  consolidate@^0.16.0:
    dependencies:
      pug: 3.0.2
      ejs: ^3.1.7
  debug@*:
    dependencies:
      supports-color: ^8.0.0
  fix-esm@1.0.1:
    dependencies:
      multer: 1.4.4-lts.1
  node-fetch@2.6.12:
    dependencies:
      encoding: ^0.1.13
  ws@8.13.0:
    dependencies:
      bufferutil: ^4.0.1
  vite@4.4.2:
    dependencies:
      bufferutil: ^4.0.1
      supports-color: ^8.0.0
  '@vitejs/plugin-vue@4.2.3':
    dependencies:
      supports-color: ^8.0.0

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux
